/* Generated By:JJTree: Do not edit this line. ASTAccess.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAccess extends SimpleNode {
  public String name = "";
  public ASTAccess(int id) {
    super(id);
  }

  public ASTAccess(yal2jvm p, int id) {
    super(p, id);
  }

  public String toString() { return yal2jvmTreeConstants.jjtNodeName[id] + " " + this.name;  }

}
/* JavaCC - OriginalChecksum=61eeed81f529eace12d3c54982c168db (do not edit this line) */
