/* Generated By:JJTree: Do not edit this line. ASTArgumentList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTArgumentList extends SimpleNode {

  public ASTArgumentList(int id) {
    super(id);
  }

  public ASTArgumentList(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=72ed0f36f33a610c97205844a6db3f61 (do not edit this line) */
