/* Generated By:JJTree: Do not edit this line. ASTElement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTElement extends SimpleNode {
  public String name = "";
  public int line = 0;

  public ASTElement(int id) {
    super(id);
  }

  public ASTElement(yal2jvm p, int id) {
    super(p, id);
  }

  public String toString() {
    return yal2jvmTreeConstants.jjtNodeName[id] + " " + this.name;
  }

}
/* JavaCC - OriginalChecksum=6d7173bfb3cb73a4e13718401265626a (do not edit this line) */
