/* Generated By:JJTree: Do not edit this line. ASTIndex.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTIndex extends SimpleNode {
  public String name = "";
  public String value = "";

  public ASTIndex(int id) {
    super(id);
  }

  public ASTIndex(yal2jvm p, int id) {
    super(p, id);
  }

  public String toString() {
    return yal2jvmTreeConstants.jjtNodeName[id] + " " + this.name + " " + this.value;
  }

}
/* JavaCC - OriginalChecksum=b2d1a61ad383c60a711ddffdf4dd360d (do not edit this line) */
