/* Generated By:JJTree: Do not edit this line. ASTSizeAccess.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTSizeAccess extends SimpleNode {
  public ASTSizeAccess(int id) {
    super(id);
  }

  public ASTSizeAccess(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1a960b7f9e7ede40faee7fb398d999ab (do not edit this line) */
