/* Generated By:JJTree: Do not edit this line. ASTSizeAccess.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSizeAccess extends SimpleNode {
  public ASTSizeAccess(int id) {
    super(id);
  }

  public ASTSizeAccess(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d011a14e93210281d1c78706f71eccb8 (do not edit this line) */
