/* Generated By:JJTree: Do not edit this line. ASTScalarAccess.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTScalarAccess extends SimpleNode {
  public String test = "Test";
  public ASTScalarAccess(int id) {
    super(id);
  }

  public ASTScalarAccess(yal2jvm p, int id) {
    super(p, id);
  }

  public String toString() { return yal2jvmTreeConstants.jjtNodeName[id] + " " + this.test;  }

}
/* JavaCC - OriginalChecksum=514488b085ed10011cacc6f9bccf328d (do not edit this line) */
