/* Generated By:JJTree: Do not edit this line. ASTVarlist.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVarlist extends SimpleNode {

  public ASTVarlist(int id) {
    super(id);
  }

  public ASTVarlist(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b3cd7de067c41fdd2dcd174445682a2f (do not edit this line) */
