/* Generated By:JJTree: Do not edit this line. ASTWhile.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWhile extends SimpleNode {

  public ASTWhile(int id) {
    super(id);
  }

  public ASTWhile(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=461acc8f2b0da7742eb2d945f8a44da5 (do not edit this line) */
