/* Generated By:JavaCC: Do not edit this line. yal2jvmTreeConstants.java Version 5.0 */
public interface yal2jvmTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTDECLARATION = 1;
  public int JJTFUNCTION = 2;
  public int JJTELEMENT = 3;
  public int JJTARRAYELEMENT = 4;
  public int JJTVARLIST = 5;
  public int JJTSCALARELEMENT = 6;
  public int JJTVOID = 7;
  public int JJTASSIGN = 8;
  public int JJTRHS = 9;
  public int JJTARRAYSIZE = 10;
  public int JJTTERM = 11;
  public int JJTEXPRTEST = 12;
  public int JJTWHILE = 13;
  public int JJTIF = 14;
  public int JJTELSE = 15;
  public int JJTCALL = 16;
  public int JJTARGUMENTLIST = 17;
  public int JJTARGUMENT = 18;
  public int JJTARRAYACCESS = 19;
  public int JJTACCESS = 20;
  public int JJTINDEX = 21;


  public String[] jjtNodeName = {
    "Module",
    "Declaration",
    "Function",
    "Element",
    "ArrayElement",
    "Varlist",
    "ScalarElement",
    "void",
    "Assign",
    "Rhs",
    "ArraySize",
    "Term",
    "Exprtest",
    "While",
    "If",
    "Else",
    "Call",
    "ArgumentList",
    "Argument",
    "ArrayAccess",
    "Access",
    "Index",
  };
}
/* JavaCC - OriginalChecksum=c896ee2c729a1d49fc49f9f7cf54c969 (do not edit this line) */
