/* Generated By:JJTree: Do not edit this line. ASTAddSub_Op.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public class ASTAddSub_Op extends SimpleNode {
  public ASTAddSub_Op(int id) {
    super(id);
  }

  public ASTAddSub_Op(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0d64268aa27dad4e10e55a0f514d6a3a (do not edit this line) */
