/* Generated By:JJTree: Do not edit this line. ASTRhs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public class ASTRhs extends SimpleNode {
  public String operator = "";

  public ASTRhs(int id) {
    super(id);
  }

  public ASTRhs(yal2jvm p, int id) {
    super(p, id);
  }

  public String toString() {
    return yal2jvmTreeConstants.jjtNodeName[id] + " " + this.operator;
  }

}
/* JavaCC - OriginalChecksum=9a93e0136e8d7562b5098c2fe72a0ac0 (do not edit this line) */
