/* Generated By:JJTree: Do not edit this line. ASTArrayElement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public class ASTArrayElement extends SimpleNode {
  public ASTArrayElement(int id) {
    super(id);
  }

  public ASTArrayElement(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=27c3d01802bef1adecdecba8018c14d4 (do not edit this line) */
