/* Generated By:JJTree: Do not edit this line. ASTAccess.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public class ASTAccess extends SimpleNode {
  public String name = "";
  public int line = 0;

  public ASTAccess(int id) {
    super(id);
  }

  public ASTAccess(yal2jvm p, int id) {
    super(p, id);
  }

  public String toString() {
    return yal2jvmTreeConstants.jjtNodeName[id] + " " + this.name;
  }

}
/* JavaCC - OriginalChecksum=8295877e5e677986d69281f76626957a (do not edit this line) */
