/* Generated By:JJTree: Do not edit this line. ASTExprtest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST; 
 
public class ASTExprtest extends SimpleNode {
  public String operator = "";

  public ASTExprtest(int id) {
    super(id);
  }

  public ASTExprtest(yal2jvm p, int id) {
    super(p, id);
  }

  public String toString() {
    return yal2jvmTreeConstants.jjtNodeName[id] + " " + this.operator;
  }

}
/* JavaCC - OriginalChecksum=b7a3adc0db16764c51f7113417fb9a79 (do not edit this line) */
