/* Generated By:JJTree: Do not edit this line. ASTIf.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST; 
 
public class ASTIf extends SimpleNode {
  public int line =0;
  public ASTIf(int id) {
    super(id);
  }

  public ASTIf(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c30988ba2783a5976b6b07bfbbf2fd0e (do not edit this line) */
