/* Generated By:JJTree: Do not edit this line. ASTScalarElement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST; 
 
public class ASTScalarElement extends SimpleNode {
  public String test = "Test";

  public ASTScalarElement(int id) {
    super(id);
  }

  public ASTScalarElement(yal2jvm p, int id) {
    super(p, id);
  }

  public String toString() {
    return yal2jvmTreeConstants.jjtNodeName[id] + " " + this.test;
  }

}
/* JavaCC - OriginalChecksum=67d6c8fe6fee892d384e37998cf60f2a (do not edit this line) */
